### ISSUE TITLE
With multiple YouTube tabs open, music playback resumes media in the first tab in order, not the last played

### ISSUE THREAD

**Issue by erayrafet** [MathiasGilson/MediaControllerChromeExtension#1]
On Windows 10 with Chrome Beta 81, in case there are a few YouTube tabs with videos open, the extension does resume playback on the first tab and not the last played one.

**Comment by MathiasGilson** [comment]
Hey @erayrafet ! Thank you for reporting this issue I updated the app and submitted a new version on the Chrome WebStore.
It should be available in a couple of days
Cheers

**Comment by erayrafet** [comment]
Thanks a ton!

**Comment by erayrafet** [comment]
@MathiasGilson Hello! I did manually load the extension and now it functions quite well. If you are a Windows user, could you please try getting the media controls to show up in the volume panel as well. Chrome used to show up those before, but they removed it. Edge does support it though.

![image](https://user-images.githubusercontent.com/34194191/78813730-217ca300-79d6-11ea-8d01-add79e74c30b.png)

![image](https://user-images.githubusercontent.com/34194191/78813820-44a75280-79d6-11ea-92e7-42b9f762e2a9.png)

**Comment by MathiasGilson** [comment]
Hello @erayrafet,
I have unfortunately no control over that as it is a feature that Chrome has to integrate.

Cheers !
